name: Generate Snake
on:
  workflow_dispatch:  # 允许手动点击运行
  schedule:
    - cron: "0 0 * * *" # 每天自动更新

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: LO-HINA
          # 这里只填用户名，其他参数统统去掉
          outputs: github-contribution-grid-snake.svg
      
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generate Snake"
          file_pattern: "github-contribution-grid-snake.svg"
